"""add mp_init_point to pedido

Revision ID: 82df92cb76ba
Revises: i9j0k1l2m3n4
Create Date: 2026-06-08 11:14:34.047784

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '82df92cb76ba'
down_revision: Union[str, None] = 'i9j0k1l2m3n4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_ingrediente_nombre_activo'), table_name='ingrediente', postgresql_where='(deleted_at IS NULL)')
    op.add_column('pedido', sa.Column('mp_init_point', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedido', 'mp_init_point')
    op.create_index(op.f('uq_ingrediente_nombre_activo'), 'ingrediente', ['nombre'], unique=True, postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###
